project:
  type: website
  output-dir: docs

website:
  title: "Md. Nazmul Islam"
  navbar:
    left:
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV
      - href: blog.qmd
        text: Blog
      - href: timeline.qmd
        text: Timeline

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">